version: '3'
services:
    express:
            build:
                context: ../
                dockerfile: db/Dockerfile
            environment:
                - DBWEBB_DSN=mongodb://mongodb:27017/trains
            volumes:
                - ../:/app/
                - /app/node_modules/
            ports:
                - 1337:1337
            command: "node app.js"
    mongodb:
        image: mongo
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --bind_ip_all